wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1650550776
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.14
      8:
      - 4
      - 5
path:
  desc: null
  value: genres_mod.parquet
