wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    t:
      1:
      - 5
      2:
      - 5
      4: 3.9.12
      5: 0.10.21
      8:
      - 4
      - 5
