wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    t:
      4: 3.9.12
      5: 0.10.21
      8:
      - 1
      - 4
      - 5
